---
- name: Custom CNI | Preflight | Start Resources
  kube:
    namespace: "{{ item.namespace | default('kube-system') }}"
    kubectl: "{{ bin_dir }}/kubectl"
    filename: "{{ item.path }}"
    state: "{{ item.state }}"
    wait: true
  loop: "{{ custom_cni_preflight_templates }}"
  delegate_to: "{{ groups['kube_control_plane'] | first }}"
  run_once: true

- name: Custom CNI | Preflight | Start Roles
  include_role:
    name: "{{ custom_cni_preflight_role }}"
  loop: "{{ custom_cni_preflight_roles }}"
  loop_control:
    loop_var: custom_cni_preflight_role
  run_once: true
